### Find All Content
GET http://localhost:8080/api/content

### Find All Content by ID
GET http://localhost:8080/api/content

### Create new Content
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "id": 2,
  "title": "My second Blog Post",
  "desc": "My 2nd blog post",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-06-10T13:25:45.324033",
  "dateUpdated": null,
  "url": ""
}


### Update existing Content
PUT http://localhost:8080/api/content/1
Content-Type: application/json

{
  "id": 1,
  "title": "MY FIRST POST",
  "desc": "MY FIRST POST",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-11-10T13:25:45.324033",
  "dateUpdated": null,
  "url": "www.google.com"
}


### Update existing Content with invalid id
PUT http://localhost:8080/api/content/100
Content-Type: application/json

{
  "id": 1,
  "title": "MY FIRST POST",
  "desc": "MY FIRST POST",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-11-10T13:25:45.324033",
  "dateUpdated": null,
  "url": "www.google.com"
}

### Delete by id
DELETE http://localhost:8080/api/content/2
